github-org-name: bloombar
github-repo-name: amos-web-site
repository: bloombar/amos-web-site
baseurl: https://i6.cims.nyu.edu/~ab1258/tmp
title: Amos Bloomberg
description: >
  Professor and practitioner of computer science, design, and development.
copyright: GNU General Public License, Version 3
layouts_dir: assets/jekyll/_layouts/
plugins:
  - "jekyll-github-metadata"
