github-org-name: bloombar
github-repo-name: amos-web-site
repository: bloombar/amos-web-site
url: https://i6.cims.nyu.edu/~ab1258/tmp
baseurl: /~ab1258/tmp
title: Amos Bloomberg
description: >
  Professor and practitioner of computer science, design, and development.
page-categories: [
    posts,
    food-and-drink,
    architecture,
    consulting,
    education,
    letters,
    music,
    family,
    me,
  ] # poems
copyright: GNU General Public License, Version 3
layouts_dir: theme/_layouts/
defaults:
  - scope:
      path: "content"
      type: pages
    values:
      layout: github
  - scope:
      path: "slides"
      type: pages
    values:
      layout: presentation
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: github
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
