github-org-name: bloombar
github-repo-name: knowledge-kitchen
repository: bloombar/amos-web-site
url: https://knowledge.kitchen
baseurl: ""
permalink: pretty
title: Knowledge Kitchen
description: >
  This site contains a somewhat organized collection of notes, mostly prepared for courses I have taught. Agile development & Devops, Software Engineering, Database Design, Web Design, Computer Programming, Computer Science, Physical Computing. Take a look.
collections:
  musings:
    output: true
  consulting:
    output: true
  domestic-construction:
    output: true
  # family:
  #   output: true
  food-and-drink:
    output: true
  me:
    output: true
  music:
    output: true
  # poems:
  #   output: true
collections_dir: content
page-categories: [
#     food-and-drink,
#     domestic-construction,
#     consulting,
    courses,
#     music,
#     me,
#     # poems
  ]
copyright: GNU General Public License, Version 3
layouts_dir: theme/_layouts/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: github
  - scope:
      path: "**/slides"
      type: pages
    values:
      layout: presentation
  - scope:
      path: "**/_posts"
      type: posts
    values:
      layout: github
  - scope:
      path: "**/_musings"
      type: "musings"
    values:
      layout: github
      categories: [musings]
  - scope:
      path: "**/_consulting"
      type: "consulting"
    values:
      layout: github
      categories: [consulting]
  - scope:
      path: "**/_domestic-construction"
      type: "domestic-construction"
    values:
      layout: github
      categories: [domestic-construction]
  - scope:
      path: "**/_family"
      type: "family"
    values:
      layout: github
      categories: [family]
  - scope:
      path: "**/_food-and-drink"
      type: "food-and-drink"
    values:
      layout: github
      categories: [food-and-drink]
  - scope:
      path: "**/_me"
      type: "me"
    values:
      layout: github
      categories: [me]
  - scope:
      path: "**/_music"
      type: "music"
    values:
      layout: github
      categories: [music]
  - scope:
      path: "**/_poems"
      type: "poems"
    values:
      layout: github
      categories: [poems]

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
